import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { fail } from "@/lib/errors";
import { uploadBuffer } from "@/lib/fileverse";
import { broadcast } from "@/services/sseManager";

const maxIdempotencyKeyLength = Number(
  process.env.MAX_IDEMPOTENCY_KEY_LENGTH || 128,
);

const isUniqueViolation = (err: unknown) =>
  err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002";

// Narrow compatibility shim for editor/type cache lag in multi-root workspaces.
const blueprintModel = () => (db as any).councilBlueprint;

const renderMarkdownFromInput = (inputJson: unknown) => {
  if (!inputJson || typeof inputJson !== "object") {
    return "# Strategic Blueprint\n\nNo structured input provided.";
  }

  const prettyJson = JSON.stringify(inputJson, null, 2);
  return [
    "# Standardized Strategic Blueprint",
    "",
    "## Council Input (Structured JSON)",
    "",
    "```json",
    prettyJson,
    "```",
    "",
    "## Execution Notes",
    "- Generated by Council Blueprint service.",
    "- Persisted to Fileverse as Markdown artifact.",
  ].join("\n");
};

export const createBlueprint = async (input: {
  requestId: string;
  createdByAgentId: string;
  title?: string | null;
  markdown?: string | null;
  inputJson?: unknown;
  idempotencyKey?: string | null;
}) => {
  const requestId = input.requestId?.trim();
  if (!requestId) throw fail("requestId is required", 400);

  const idempotencyKey = input.idempotencyKey?.trim() || null;
  if (idempotencyKey && idempotencyKey.length > maxIdempotencyKeyLength) {
    throw fail(
      `Idempotency key exceeds max length (${maxIdempotencyKeyLength})`,
      400,
    );
  }

  if (idempotencyKey) {
    const existing = await blueprintModel().findFirst({
      where: {
        requestId,
        idempotencyKey,
      },
    });
    if (existing) return existing;
  }

  const markdown =
    input.markdown?.trim() || renderMarkdownFromInput(input.inputJson);
  const filename = `blueprint-${requestId}.md`;

  const uploaded = await uploadBuffer({
    file: Buffer.from(markdown, "utf-8"),
    filename,
    mimeType: "text/markdown",
  });

  try {
    const row = await blueprintModel().create({
      data: {
        requestId,
        createdByAgentId: input.createdByAgentId,
        title: input.title?.trim() || null,
        markdown,
        inputJson: input.inputJson == null ? Prisma.DbNull : input.inputJson,
        fileverseDocId: uploaded.docId,
        storageRef: uploaded.storageRef,
        contentHash: uploaded.contentHash,
        idempotencyKey,
        status: "generated",
      },
    });

    broadcast("council.blueprint.generated", {
      blueprintId: row.id,
      requestId: row.requestId,
      createdByAgentId: row.createdByAgentId,
      storageRef: row.storageRef,
    });

    return row;
  } catch (err) {
    if (isUniqueViolation(err)) {
      const byRequest = await blueprintModel().findUnique({
        where: { requestId },
      });
      if (byRequest) return byRequest;
    }
    throw err;
  }
};

export const listBlueprints = async (input: {
  createdByAgentId: string;
  status?: "generated" | "archived" | null;
}) => {
  return blueprintModel().findMany({
    where: {
      createdByAgentId: input.createdByAgentId,
      ...(input.status ? { status: input.status } : {}),
    },
    orderBy: { createdAt: "desc" },
  });
};

export const getBlueprintById = async (id: string, requesterId: string) => {
  const row = await blueprintModel().findUnique({ where: { id } });
  if (!row) throw fail("Blueprint not found", 404);
  if (row.createdByAgentId && row.createdByAgentId !== requesterId) {
    throw fail("Forbidden", 403);
  }
  return row;
};

export const getBlueprintAttachReference = async (
  blueprintId: string,
  requesterId: string,
) => {
  const blueprint = await blueprintModel().findUnique({
    where: { id: blueprintId },
    select: {
      id: true,
      createdByAgentId: true,
      storageRef: true,
      contentHash: true,
      fileverseDocId: true,
    },
  });

  if (!blueprint) throw fail("Blueprint not found", 404);
  if (
    blueprint.createdByAgentId &&
    blueprint.createdByAgentId !== requesterId
  ) {
    throw fail("Forbidden", 403);
  }

  return {
    blueprintId: blueprint.id,
    blueprintRef: blueprint.storageRef,
    blueprintHash: blueprint.contentHash,
    fileverseDocId: blueprint.fileverseDocId,
  };
};
